spring:
  application:
    name: oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://token.actions.githubusercontent.com
          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks