server:
  port : 8082
spring:
  application:
    name: oauth2-resource-server-token-propagation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spmia-realm