version: '3.3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - start-dev
      - --import-realm
    ports:
      - "8180:8080"
    networks:
      backend:
        aliases:
          - "keycloak"
networks:
  backend:
    driver: bridge